// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdwvyeuxrbwoggeysqgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkd3Z5ZXV4cmJ3b2dnZXlzcWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjAzMzksImV4cCI6MjA3NDI5NjMzOX0.ooQH9ydDF7UaNMASdFB19xaStJAaH1G5YEJ1kt_Efx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});